'use client';
import { ArrowUpRight, Minus, Plus, ShoppingBag } from 'lucide-react';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { PageHero, SiteShell } from '@/app/components/SiteShell';
import { plans } from '@/app/site-data';

export default function PreisePage() { return <SiteShell>
  <PageHero index="02 / Preise" eyebrow="Choose your movement" title={<>Einfach wählen.<br/><em>Direkt loslegen.</em></>} text="Alle Pakete klar im Vergleich und für die sichere Übergabe an bsport vorbereitet." />
  <section className="prices standalone-prices"><div className="prices-head"><p className="eyebrow">Dein Rhythmus</p><h2>New here.<br/><em>Want more.</em><br/>Exclusive.</h2><p>Öffne eine Kategorie, vergleiche die Optionen und wähle dein Paket.</p></div><Accordion defaultValue={['new']} className="pricing-accordion">{plans.map((plan,index) => <AccordionItem value={plan.value} key={plan.value} className="pricing-item"><AccordionTrigger className="pricing-trigger"><span className="plan-count">0{index+1}</span><span><small>{plan.kicker}</small>{plan.name}</span><span className="plan-symbol"><Plus className="plus"/><Minus className="minus"/></span></AccordionTrigger><AccordionContent className="pricing-content"><p className="plan-description">{plan.description}</p><div className="offer-grid">{plan.offers.map(offer => <article className="offer-card" key={offer.title}><div><p className="offer-type">Eora Move Pass</p><h3>{offer.title}</h3></div><dl><div><dt>Einheiten</dt><dd>{offer.sessions}</dd></div><div><dt>Gültigkeit</dt><dd>{offer.validity}</dd></div></dl><div className="offer-bottom"><strong>{offer.price}</strong><a href="/login">In den Warenkorb <ShoppingBag/></a></div></article>)}</div></AccordionContent></AccordionItem>)}</Accordion></section>
  <section className="booking-flow"><p className="section-index">So einfach geht’s</p><h2>Four steps.<br/>One good decision.</h2><ol>{['Termin auswählen','Paket wählen','Einloggen','Buchung abschließen'].map((step,index)=><li key={step}><span>0{index+1}</span><p>{step}</p>{index<3&&<ArrowUpRight/>}</li>)}</ol><a className="button button-primary" href="/login">Zu bsport <ArrowUpRight/></a></section>
  </SiteShell>; }
